"""personalcapital2 — Python client for the Empower (Personal Capital) unofficial API."""

from personalcapital2.auth import authenticate
from personalcapital2.client import EmpowerClient
from personalcapital2.exceptions import EmpowerAPIError, EmpowerAuthError, TwoFactorRequiredError
from personalcapital2.models import (
    Account,
    AccountBalance,
    AccountPerformanceSummary,
    AccountsResult,
    AccountsSummary,
    BenchmarkPerformance,
    Category,
    Holding,
    HoldingsResult,
    InvestmentPerformance,
    MarketQuote,
    NetWorthEntry,
    NetWorthResult,
    NetWorthSummary,
    PerformanceResult,
    PortfolioSnapshot,
    PortfolioVsBenchmark,
    QuotesResult,
    SpendingDetail,
    SpendingSummary,
    Transaction,
    TransactionsResult,
    TransactionsSummary,
)
from personalcapital2.types import TwoFactorMode

__all__ = [
    "Account",
    "AccountBalance",
    "AccountPerformanceSummary",
    "AccountsResult",
    "AccountsSummary",
    "BenchmarkPerformance",
    "Category",
    "EmpowerAPIError",
    "EmpowerAuthError",
    "EmpowerClient",
    "Holding",
    "HoldingsResult",
    "InvestmentPerformance",
    "MarketQuote",
    "NetWorthEntry",
    "NetWorthResult",
    "NetWorthSummary",
    "PerformanceResult",
    "PortfolioSnapshot",
    "PortfolioVsBenchmark",
    "QuotesResult",
    "SpendingDetail",
    "SpendingSummary",
    "Transaction",
    "TransactionsResult",
    "TransactionsSummary",
    "TwoFactorMode",
    "TwoFactorRequiredError",
    "authenticate",
]
